[package]
org = "ballerinax"
name = "aws.lambda"
version = "3.3.1"
distribution = "2201.11.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.lambda"
license = ["Apache-2.0"]
keywords = ["aws", "lambda", "serverless", "cloud", "Vendor/Amazon", "Area/Other", "Type/Util"]

[platform.java21]
graalvmCompatible = true
