name: Ballerina AWS Lambda Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1
      SAM_CLI_TELEMETRY: 0
      GITHUB_TOKEN: ${{ secrets.BALLERINA_STDLIB_TOKEN }}
      packageUser: ${{ github.actor }}
      packagePAT: ${{ secrets.BALLERINA_STDLIB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Set up Docker
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Setup Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: '3.7'
      - name: Install aws-sam-cli
        run: pip install aws-sam-cli
      - name: Build with gradle
        run: ./gradlew clean build -PLayerTesting --stacktrace --scan --console=plain --no-daemon
